apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbitwebui.fullname" . }}-web
  labels:
    {{- include "qbitwebui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "qbitwebui.selectorLabels" . | nindent 4 }}